# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano//zmk" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9//zmk
#   - board: nice_nano//zmk
#     shield: reviung41
#
---
include:
  # Hillside 48 - using new ZMK board naming convention (Zephyr 4.1+)
  - board: nice_nano//zmk
    shield: hillside48_left
  - board: nice_nano//zmk
    shield: hillside48_right
